function scopedStudyWords(){if(state.studyTopicId==='__saved')return state.words.filter(w=>w.saved);if(state.studyTopicId)return state.words.filter(w=>w.topicId===state.studyTopicId);return null}
async function loadStudy(){const box=document.getElementById('vocabContent');box.innerHTML='<div class="leitner-loading">Đang chuẩn bị thẻ…</div>';try{state.due=scopedStudyWords()||await api('/api/study/due');state.studyBoxFilter=0;state.cardIndex=0;state.cardFlipped=false;renderStudy()}catch(error){box.innerHTML=`<div class="leitner-empty">${esc(error.message)}</div>`}}
function renderStudy(){const box=document.getElementById('vocabContent'),w=state.due[state.cardIndex],dist=state.analytics.distribution||{},topic=w?topicName(w.topicId):'',primary=state.cardFlipped?(w?.vietnamese||'Chưa có nghĩa'):w?.english,secondary=state.cardFlipped?(arr(w?.examples)[0]||w?.definition||'Chưa có gợi ý'):w?.phonetic,wordSize=(primary||'').length>20?34:(primary||'').length>13?40:48,wordTransform=state.cardFlipped?'none':'capitalize';box.innerHTML=`<section class="leitner-review"><article class="leitner-review-card"><div class="leitner-review-meta"><span><i></i>${w?`CHỦ ĐỀ: ${esc(topic)}`:'HOÀN THÀNH'}</span><b>Card ${w?state.cardIndex+1:0} of ${state.due.length}</b></div><div class="leitner-word">${w?`<h2 style="font-size:${wordSize}px;text-transform:${wordTransform}">${esc(primary)}</h2><p>${esc(secondary||'Chưa có phiên âm')}</p><button type="button" onclick="flipCard()"><img src="${A}lightbulb.svg" alt="">${state.cardFlipped?'Ẩn gợi ý':'Gợi ý'}</button>`:`<h2>${state.studyTopicId?'Bộ thẻ chưa có từ':'Hoàn thành phiên '+state.session+'!'}</h2><p>${state.studyTopicId?'Hãy quay lại và chọn một bộ từ khác.':'Không còn từ đến hạn trong danh sách này.'}</p><button type="button" onclick="${state.studyTopicId?'returnToVocabulary()':'advanceSession()'}">${state.studyTopicId?'Quay lại bộ chủ đề':'Sang phiên kế'}</button>`}</div><div class="leitner-rating"><h3>MỨC ĐỘ NHỚ CỦA BẠN LÀ BAO NHIÊU ?</h3><div><button class="again" ${w?'':'disabled'} onclick="review('AGAIN')"><strong>Review Again</strong><small>Xem lại</small></button><button class="hard" ${w?'':'disabled'} onclick="review('HARD')"><strong>Hard</strong><small>Khó</small></button><button class="easy" ${w?'':'disabled'} onclick="review('EASY')"><strong>Easy</strong><small>Thuộc lòng</small></button></div></div></article><button class="leitner-arrow previous" type="button" aria-label="Thẻ trước" onclick="previousStudyCard()" ${state.due.length>1?'':'disabled'}><img src="${A}leitner-arrow.svg" alt=""></button><button class="leitner-arrow next" type="button" aria-label="Thẻ tiếp theo" onclick="nextStudyCard()" ${state.due.length>1?'':'disabled'}><img src="${A}leitner-arrow.svg" alt=""></button></section><section class="leitner-boxes">${leitnerBoxCard(1,dist.level1||0,'Khó','Daily Review','Những từ quên nhiều, ôn tập mỗi ngày','red')}${leitnerBoxCard(2,dist.level2||0,'Vừa','Every 3 Days','Những từ bạn đã biết, ôn tập 3 lần mỗi tuần','yellow')}${leitnerBoxCard(3,dist.level3||0,'Dễ','Mastered','Những từ thuộc lòng, ôn tập mỗi tuần 1 lần','green')}</section>`}
function leitnerBoxCard(level,count,difficulty,schedule,description,color){return `<article class="leitner-box ${color} ${state.studyBoxFilter===level?'selected':''}"><div class="leitner-box-top"><span>BOX ${level}</span><b>${difficulty}</b></div><div class="leitner-box-count"><small>${schedule}</small><strong>${count.toLocaleString('vi-VN')} <em>từ</em></strong></div><p>${description}</p><button type="button" onclick="studyBox(${level})">Ôn tập <img src="${A}leitner-chevron-${color}.svg" alt=""></button></article>`}
function flipCard(){state.cardFlipped=!state.cardFlipped;renderStudy()}
function previousStudyCard(){if(!state.due.length)return;state.cardIndex=(state.cardIndex-1+state.due.length)%state.due.length;state.cardFlipped=false;renderStudy()}
function nextStudyCard(){if(!state.due.length)return;state.cardIndex=(state.cardIndex+1)%state.due.length;state.cardFlipped=false;renderStudy()}
function studyBox(level){const words=(scopedStudyWords()||state.words).filter(w=>w.progress?.isLearned&&w.progress.level===level);if(!words.length)return toast(`Hộp ${level} chưa có từ`,true);state.due=words;state.studyBoxFilter=level;state.cardIndex=0;state.cardFlipped=false;renderStudy()}
async function review(rating,e){e?.stopPropagation();const w=state.due[state.cardIndex];try{await api('/api/study/review',{method:'POST',body:JSON.stringify({wordId:w.id,rating})});state.cardIndex++;state.cardFlipped=false;if(state.cardIndex>=state.due.length){await refreshData(false);state.due=[];return returnToVocabulary('Đã hoàn thành bộ Flashcard')}renderStudy()}catch(error){toast(error.message,true)}}
async function advanceSession(){try{const result=await api('/api/study/session/advance',{method:'POST'});state.session=result.currentSession;syncShell();toast(`Đã chuyển sang phiên ${state.session}`);loadStudy()}catch(error){toast(error.message,true)}}
function openStudy(){state.studyTopicId='';state.vocabTab='study';go('vocabulary')}
function startSavedStudy(){const words=state.words.filter(w=>w.saved);if(!words.length)return toast('Chưa có từ đã lưu để ôn tập',true);state.studyTopicId='__saved';state.due=words;state.vocabTab='study';state.view='vocabulary';syncShell();view.innerHTML=`<section class="leitner-page"><header class="leitner-heading"><h1>Học Thuộc Leitner</h1><p>Ôn tập toàn bộ những từ bạn đã lưu.</p></header><div id="vocabContent" class="leitner-content"></div></section>`;state.studyBoxFilter=0;state.cardIndex=0;state.cardFlipped=false;renderStudy()}
function returnToVocabulary(message=''){state.studyTopicId='';state.vocabTab='topics';syncShell();renderVocabulary();if(message)toast(message)}
